/**
 * Requirements Generator
 * Generates Python requirements.txt with all dependencies.
 */

import { writeFileSync } from "node:fs";
import { ShepSpec } from "@goldensheepai/shep-core";

export function generateRequirements(spec: ShepSpec, outputDir: string, hasAI: boolean): void {
  let requirements = `# Generated requirements for ${spec.app}
# Install with: pip install -r requirements.txt

# Web Framework
fastapi>=0.104.0
uvicorn[standard]>=0.24.0

# Data Validation
pydantic>=2.5.0
pydantic[email]>=2.5.0

# Authentication
python-jose[cryptography]>=3.3.0
passlib[bcrypt]>=1.7.4
PyJWT>=2.8.0

# Database (add your preferred database driver)
# sqlalchemy>=2.0.0
# asyncpg>=0.29.0  # PostgreSQL
# aiosqlite>=0.19.0  # SQLite

# Utilities
python-multipart>=0.0.6
python-dotenv>=1.0.0
`;

  if (hasAI) {
    requirements += `
# AI/LLM (for AI primitives)
httpx>=0.25.0
`;
  }

  writeFileSync(`${outputDir}/requirements.txt`, requirements);
  console.log(`  ✓ ${outputDir}/requirements.txt`);

  // Also generate __init__.py for Python package
  const initPy = `# Generated by Shep Compiler
# This makes the generated directory a Python package
`;
  writeFileSync(`${outputDir}/__init__.py`, initPy);
  console.log(`  ✓ ${outputDir}/__init__.py`);
}
