/**
 * Styling Generator
 *
 * Generates Tailwind CSS configuration and styled components
 * for non-technical founders who want beautiful apps.
 */

import { writeFileSync } from "node:fs";
import { ShepSpec, Entity, Field } from "@shep/core";

/**
 * Generate all styling assets for the frontend.
 */
export function generateStyles(spec: ShepSpec, outputDir: string): void {
  generateTailwindConfig(spec, outputDir);
  generateGlobalCSS(spec, outputDir);
  generateUIComponents(spec, outputDir);
}

/**
 * Generate Tailwind CSS configuration.
 */
function generateTailwindConfig(spec: ShepSpec, outputDir: string): void {
  const config = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./*.{html,js}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand colors - customize for your app
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'spin-slow': 'spin 2s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
`;

  writeFileSync(`${outputDir}/tailwind.config.js`, config);
  console.log(`  ✓ ${outputDir}/tailwind.config.js`);
}

/**
 * Generate global CSS with Tailwind directives.
 */
function generateGlobalCSS(spec: ShepSpec, outputDir: string): void {
  const css = `/* Generated by Shep Compiler for ${spec.app} */
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Custom base styles */
@layer base {
  html {
    @apply scroll-smooth;
  }
  
  body {
    @apply bg-gray-50 text-gray-900 antialiased;
    font-feature-settings: "cv02", "cv03", "cv04", "cv11";
  }
  
  /* Better focus states for accessibility */
  *:focus-visible {
    @apply outline-2 outline-offset-2 outline-primary-500;
  }
  
  /* Remove default button styles */
  button {
    @apply cursor-pointer;
  }
}

/* Reusable component classes */
@layer components {
  /* Cards */
  .card {
    @apply bg-white rounded-xl shadow-sm border border-gray-200 p-6;
  }
  
  .card-hover {
    @apply card transition-shadow hover:shadow-md;
  }
  
  /* Buttons */
  .btn {
    @apply inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none;
  }
  
  .btn-primary {
    @apply btn bg-primary-600 text-white hover:bg-primary-700 focus:ring-primary-500;
  }
  
  .btn-secondary {
    @apply btn bg-gray-100 text-gray-700 hover:bg-gray-200 focus:ring-gray-500;
  }
  
  .btn-outline {
    @apply btn border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 focus:ring-primary-500;
  }
  
  .btn-danger {
    @apply btn bg-red-600 text-white hover:bg-red-700 focus:ring-red-500;
  }
  
  .btn-ghost {
    @apply btn bg-transparent text-gray-600 hover:bg-gray-100 focus:ring-gray-500;
  }
  
  .btn-sm {
    @apply px-3 py-1.5 text-xs;
  }
  
  .btn-lg {
    @apply px-6 py-3 text-base;
  }
  
  /* Form inputs */
  .input {
    @apply w-full px-3 py-2 text-sm border border-gray-300 rounded-lg bg-white transition-colors placeholder:text-gray-400 focus:border-primary-500 focus:ring-1 focus:ring-primary-500;
  }
  
  .input-error {
    @apply border-red-500 focus:border-red-500 focus:ring-red-500;
  }
  
  .label {
    @apply block text-sm font-medium text-gray-700 mb-1;
  }
  
  .form-group {
    @apply space-y-1;
  }
  
  .form-error {
    @apply text-sm text-red-600 mt-1;
  }
  
  /* Select */
  .select {
    @apply input appearance-none bg-no-repeat bg-right pr-10;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
    background-size: 1.5em 1.5em;
    background-position: right 0.5rem center;
  }
  
  /* Checkbox and Radio */
  .checkbox {
    @apply w-4 h-4 rounded border-gray-300 text-primary-600 focus:ring-primary-500;
  }
  
  .radio {
    @apply w-4 h-4 border-gray-300 text-primary-600 focus:ring-primary-500;
  }
  
  /* Badges */
  .badge {
    @apply inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium;
  }
  
  .badge-primary {
    @apply badge bg-primary-100 text-primary-800;
  }
  
  .badge-success {
    @apply badge bg-green-100 text-green-800;
  }
  
  .badge-warning {
    @apply badge bg-yellow-100 text-yellow-800;
  }
  
  .badge-danger {
    @apply badge bg-red-100 text-red-800;
  }
  
  .badge-gray {
    @apply badge bg-gray-100 text-gray-800;
  }
  
  /* Tables */
  .table {
    @apply w-full text-sm text-left;
  }
  
  .table th {
    @apply px-4 py-3 font-medium text-gray-500 uppercase tracking-wider bg-gray-50 border-b;
  }
  
  .table td {
    @apply px-4 py-3 border-b border-gray-100;
  }
  
  .table tr:hover td {
    @apply bg-gray-50;
  }
  
  /* Modal */
  .modal-overlay {
    @apply fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50 animate-fade-in;
  }
  
  .modal {
    @apply bg-white rounded-xl shadow-xl w-full max-w-md animate-slide-up;
  }
  
  .modal-header {
    @apply flex items-center justify-between px-6 py-4 border-b;
  }
  
  .modal-body {
    @apply px-6 py-4;
  }
  
  .modal-footer {
    @apply flex justify-end gap-3 px-6 py-4 border-t bg-gray-50 rounded-b-xl;
  }
  
  /* Alert */
  .alert {
    @apply p-4 rounded-lg border;
  }
  
  .alert-info {
    @apply alert bg-blue-50 border-blue-200 text-blue-800;
  }
  
  .alert-success {
    @apply alert bg-green-50 border-green-200 text-green-800;
  }
  
  .alert-warning {
    @apply alert bg-yellow-50 border-yellow-200 text-yellow-800;
  }
  
  .alert-error {
    @apply alert bg-red-50 border-red-200 text-red-800;
  }
  
  /* Loading spinner */
  .spinner {
    @apply w-5 h-5 border-2 border-gray-200 border-t-primary-600 rounded-full animate-spin;
  }
  
  /* Empty state */
  .empty-state {
    @apply flex flex-col items-center justify-center py-12 text-center;
  }
  
  .empty-state-icon {
    @apply w-12 h-12 text-gray-300 mb-4;
  }
  
  .empty-state-title {
    @apply text-lg font-medium text-gray-900;
  }
  
  .empty-state-description {
    @apply text-sm text-gray-500 mt-1;
  }
}

/* Utility classes */
@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
  
  .scrollbar-hide {
    -ms-overflow-style: none;
    scrollbar-width: none;
  }
  
  .scrollbar-hide::-webkit-scrollbar {
    display: none;
  }
}
`;

  writeFileSync(`${outputDir}/styles.css`, css);
  console.log(`  ✓ ${outputDir}/styles.css`);
}

/**
 * Generate reusable UI components in React with TypeScript.
 */
function generateUIComponents(spec: ShepSpec, outputDir: string): void {
  const components = `// Generated UI Components for ${spec.app}
// Built with Tailwind CSS + React patterns inspired by shadcn/ui
// DO NOT EDIT - regenerate from .shep file

import React, { ReactNode, ButtonHTMLAttributes, InputHTMLAttributes, SelectHTMLAttributes, forwardRef } from 'react';

// =============================================================================
// Button Component
// =============================================================================

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'danger' | 'ghost';
type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  children: ReactNode;
}

const buttonVariants: Record<ButtonVariant, string> = {
  primary: 'bg-primary-600 text-white hover:bg-primary-700 focus:ring-primary-500',
  secondary: 'bg-gray-100 text-gray-700 hover:bg-gray-200 focus:ring-gray-500',
  outline: 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 focus:ring-primary-500',
  danger: 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500',
  ghost: 'bg-transparent text-gray-600 hover:bg-gray-100 focus:ring-gray-500',
};

const buttonSizes: Record<ButtonSize, string> = {
  sm: 'px-3 py-1.5 text-xs',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
};

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = 'primary', size = 'md', loading, children, className = '', disabled, ...props }, ref) => {
    const baseClasses = 'inline-flex items-center justify-center gap-2 font-medium rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none';
    
    return (
      <button
        ref={ref}
        className={\`\${baseClasses} \${buttonVariants[variant]} \${buttonSizes[size]} \${className}\`}
        disabled={disabled || loading}
        {...props}
      >
        {loading && <span className="spinner" />}
        {children}
      </button>
    );
  }
);
Button.displayName = 'Button';

// =============================================================================
// Input Component
// =============================================================================

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ label, error, className = '', ...props }, ref) => {
    return (
      <div className="form-group">
        {label && <label className="label">{label}</label>}
        <input
          ref={ref}
          className={\`input \${error ? 'input-error' : ''} \${className}\`}
          {...props}
        />
        {error && <p className="form-error">{error}</p>}
      </div>
    );
  }
);
Input.displayName = 'Input';

// =============================================================================
// Select Component
// =============================================================================

interface SelectProps extends SelectHTMLAttributes<HTMLSelectElement> {
  label?: string;
  error?: string;
  options: { value: string; label: string }[];
}

export const Select = forwardRef<HTMLSelectElement, SelectProps>(
  ({ label, error, options, className = '', ...props }, ref) => {
    return (
      <div className="form-group">
        {label && <label className="label">{label}</label>}
        <select
          ref={ref}
          className={\`select \${error ? 'input-error' : ''} \${className}\`}
          {...props}
        >
          {options.map((opt) => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
        {error && <p className="form-error">{error}</p>}
      </div>
    );
  }
);
Select.displayName = 'Select';

// =============================================================================
// Card Component
// =============================================================================

interface CardProps {
  children: ReactNode;
  className?: string;
  hover?: boolean;
}

export function Card({ children, className = '', hover = false }: CardProps) {
  return (
    <div className={\`\${hover ? 'card-hover' : 'card'} \${className}\`}>
      {children}
    </div>
  );
}

export function CardHeader({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <div className={\`mb-4 \${className}\`}>{children}</div>;
}

export function CardTitle({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <h3 className={\`text-lg font-semibold text-gray-900 \${className}\`}>{children}</h3>;
}

export function CardDescription({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <p className={\`text-sm text-gray-500 mt-1 \${className}\`}>{children}</p>;
}

export function CardContent({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <div className={className}>{children}</div>;
}

// =============================================================================
// Badge Component
// =============================================================================

type BadgeVariant = 'primary' | 'success' | 'warning' | 'danger' | 'gray';

interface BadgeProps {
  variant?: BadgeVariant;
  children: ReactNode;
  className?: string;
}

const badgeVariants: Record<BadgeVariant, string> = {
  primary: 'bg-primary-100 text-primary-800',
  success: 'bg-green-100 text-green-800',
  warning: 'bg-yellow-100 text-yellow-800',
  danger: 'bg-red-100 text-red-800',
  gray: 'bg-gray-100 text-gray-800',
};

export function Badge({ variant = 'gray', children, className = '' }: BadgeProps) {
  return (
    <span className={\`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium \${badgeVariants[variant]} \${className}\`}>
      {children}
    </span>
  );
}

// =============================================================================
// Modal Component
// =============================================================================

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title?: string;
  children: ReactNode;
  footer?: ReactNode;
}

export function Modal({ open, onClose, title, children, footer }: ModalProps) {
  if (!open) return null;
  
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        {title && (
          <div className="modal-header">
            <h2 className="text-lg font-semibold text-gray-900">{title}</h2>
            <button onClick={onClose} className="btn-ghost p-1 rounded-lg">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        )}
        <div className="modal-body">{children}</div>
        {footer && <div className="modal-footer">{footer}</div>}
      </div>
    </div>
  );
}

// =============================================================================
// Alert Component
// =============================================================================

type AlertVariant = 'info' | 'success' | 'warning' | 'error';

interface AlertProps {
  variant?: AlertVariant;
  title?: string;
  children: ReactNode;
  className?: string;
}

const alertVariants: Record<AlertVariant, string> = {
  info: 'bg-blue-50 border-blue-200 text-blue-800',
  success: 'bg-green-50 border-green-200 text-green-800',
  warning: 'bg-yellow-50 border-yellow-200 text-yellow-800',
  error: 'bg-red-50 border-red-200 text-red-800',
};

export function Alert({ variant = 'info', title, children, className = '' }: AlertProps) {
  return (
    <div className={\`p-4 rounded-lg border \${alertVariants[variant]} \${className}\`}>
      {title && <p className="font-medium mb-1">{title}</p>}
      <p className="text-sm">{children}</p>
    </div>
  );
}

// =============================================================================
// Loading Spinner
// =============================================================================

interface SpinnerProps {
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

const spinnerSizes = {
  sm: 'w-4 h-4 border',
  md: 'w-6 h-6 border-2',
  lg: 'w-8 h-8 border-2',
};

export function Spinner({ size = 'md', className = '' }: SpinnerProps) {
  return (
    <div className={\`\${spinnerSizes[size]} border-gray-200 border-t-primary-600 rounded-full animate-spin \${className}\`} />
  );
}

// =============================================================================
// Empty State
// =============================================================================

interface EmptyStateProps {
  icon?: ReactNode;
  title: string;
  description?: string;
  action?: ReactNode;
}

export function EmptyState({ icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="empty-state">
      {icon && <div className="empty-state-icon">{icon}</div>}
      <h3 className="empty-state-title">{title}</h3>
      {description && <p className="empty-state-description">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// =============================================================================
// Table Components
// =============================================================================

interface TableProps {
  children: ReactNode;
  className?: string;
}

export function Table({ children, className = '' }: TableProps) {
  return (
    <div className="overflow-x-auto">
      <table className={\`table \${className}\`}>{children}</table>
    </div>
  );
}

export function TableHeader({ children }: { children: ReactNode }) {
  return <thead>{children}</thead>;
}

export function TableBody({ children }: { children: ReactNode }) {
  return <tbody>{children}</tbody>;
}

export function TableRow({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <tr className={className}>{children}</tr>;
}

export function TableHead({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <th className={className}>{children}</th>;
}

export function TableCell({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <td className={className}>{children}</td>;
}
`;

  writeFileSync(`${outputDir}/components.tsx`, components);
  console.log(`  ✓ ${outputDir}/components.tsx`);
}
