'use client';

import { useState } from 'react';

const API_BASE = 'http://localhost:3001/api';

export default function Home() {
  const [message, setMessage] = useState('');
  const [sentiment, setSentiment] = useState<string | null>(null);
  const [summary, setSummary] = useState<string | null>(null);
  const [isEscalated, setIsEscalated] = useState<boolean | null>(null);
  const [isSpam, setIsSpam] = useState<boolean | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const analyzeMessage = async () => {
    if (!message.trim()) return;
    
    setLoading(true);
    setError(null);
    setSentiment(null);
    setSummary(null);
    setIsEscalated(null);
    setIsSpam(null);

    try {
      // Analyze sentiment
      const sentimentRes = await fetch(`${API_BASE}/ai/message_sentiment`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: message }),
      });
      if (sentimentRes.ok) {
        const data = await sentimentRes.json();
        setSentiment(data.result);
      }

      // Generate summary
      const summaryRes = await fetch(`${API_BASE}/ai/message_summary`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: message }),
      });
      if (summaryRes.ok) {
        const data = await summaryRes.json();
        setSummary(data.result);
      }

      // Check if frustrated (rule 1)
      const escalateRes = await fetch(`${API_BASE}/ai/rule_1`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message_content: message }),
      });
      if (escalateRes.ok) {
        const data = await escalateRes.json();
        setIsEscalated(data.result === 'true');
      }

      // Check if spam (rule 2)
      const spamRes = await fetch(`${API_BASE}/ai/rule_2`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message_content: message }),
      });
      if (spamRes.ok) {
        const data = await spamRes.json();
        setIsSpam(data.result === 'true');
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to analyze');
    } finally {
      setLoading(false);
    }
  };

  return (
    <main style={{ 
      maxWidth: '800px', 
      margin: '0 auto', 
      padding: '40px 20px',
      fontFamily: 'system-ui, -apple-system, sans-serif'
    }}>
      <h1 style={{ marginBottom: '8px' }}>🐑 SupportAI</h1>
      <p style={{ color: '#666', marginBottom: '32px' }}>
        AI-powered customer support demo - Generated by Shep
      </p>

      <div style={{ 
        background: '#f5f5f5', 
        padding: '20px', 
        borderRadius: '8px',
        marginBottom: '24px'
      }}>
        <h2 style={{ marginTop: 0, marginBottom: '16px' }}>AI Message Analysis</h2>
        
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          placeholder="Enter a customer message to analyze..."
          style={{
            width: '100%',
            minHeight: '100px',
            padding: '12px',
            fontSize: '16px',
            borderRadius: '4px',
            border: '1px solid #ddd',
            marginBottom: '12px',
            resize: 'vertical',
          }}
        />

        <button
          onClick={analyzeMessage}
          disabled={loading || !message.trim()}
          style={{
            padding: '12px 24px',
            fontSize: '16px',
            background: loading ? '#ccc' : '#0070f3',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            cursor: loading ? 'not-allowed' : 'pointer',
          }}
        >
          {loading ? 'Analyzing...' : 'Analyze with AI'}
        </button>

        {error && (
          <p style={{ color: 'red', marginTop: '12px' }}>
            ⚠️ {error}
            <br />
            <small>Make sure ANTHROPIC_API_KEY is set and the backend is running.</small>
          </p>
        )}
      </div>

      {(sentiment || summary || isEscalated !== null || isSpam !== null) && (
        <div style={{ 
          background: 'white', 
          padding: '20px', 
          borderRadius: '8px',
          border: '1px solid #ddd'
        }}>
          <h3 style={{ marginTop: 0 }}>Analysis Results</h3>
          
          <div style={{ display: 'grid', gap: '16px' }}>
            {sentiment && (
              <div>
                <strong>Sentiment:</strong>{' '}
                <span style={{
                  padding: '4px 8px',
                  borderRadius: '4px',
                  background: sentiment.toLowerCase().includes('positive') ? '#d4edda' :
                             sentiment.toLowerCase().includes('negative') ? '#f8d7da' : '#fff3cd',
                  color: sentiment.toLowerCase().includes('positive') ? '#155724' :
                         sentiment.toLowerCase().includes('negative') ? '#721c24' : '#856404',
                }}>
                  {sentiment}
                </span>
              </div>
            )}

            {summary && (
              <div>
                <strong>Summary:</strong> {summary}
              </div>
            )}

            {isEscalated !== null && (
              <div>
                <strong>Should Escalate:</strong>{' '}
                <span style={{
                  padding: '4px 8px',
                  borderRadius: '4px',
                  background: isEscalated ? '#f8d7da' : '#d4edda',
                  color: isEscalated ? '#721c24' : '#155724',
                }}>
                  {isEscalated ? '⚠️ Yes - Customer sounds frustrated' : '✅ No - Customer seems okay'}
                </span>
              </div>
            )}

            {isSpam !== null && (
              <div>
                <strong>Spam Detection:</strong>{' '}
                <span style={{
                  padding: '4px 8px',
                  borderRadius: '4px',
                  background: isSpam ? '#f8d7da' : '#d4edda',
                  color: isSpam ? '#721c24' : '#155724',
                }}>
                  {isSpam ? '🚫 Flagged as spam' : '✅ Not spam'}
                </span>
              </div>
            )}
          </div>
        </div>
      )}

      <div style={{ marginTop: '40px', color: '#888', fontSize: '14px' }}>
        <h4>Try these example messages:</h4>
        <ul>
          <li onClick={() => setMessage("I'm so frustrated! Your product keeps crashing and nobody is helping me. This is unacceptable!")} style={{ cursor: 'pointer', color: '#0070f3' }}>
            😠 Frustrated customer
          </li>
          <li onClick={() => setMessage("Hi! I love your product. Just wanted to say thanks for the great service!")} style={{ cursor: 'pointer', color: '#0070f3' }}>
            😊 Happy customer
          </li>
          <li onClick={() => setMessage("AMAZING OFFER! Buy now and get 50% off! Limited time only! Click here to claim your prize!")} style={{ cursor: 'pointer', color: '#0070f3' }}>
            📧 Spam message
          </li>
          <li onClick={() => setMessage("I need help resetting my password. Can someone assist me?")} style={{ cursor: 'pointer', color: '#0070f3' }}>
            🔑 Normal support request
          </li>
        </ul>
      </div>

      <footer style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid #eee', color: '#888', fontSize: '12px' }}>
        Generated by <strong>Shep Compiler</strong> from <code>app.shep</code> | 
        AI features powered by <code>ai()</code> primitives | 
        <a href="http://localhost:3001/docs" style={{ marginLeft: '4px' }}>API Docs</a>
      </footer>
    </main>
  );
}
